### ISSUE TITLE
Reduce number of edges by only saving folders

### ISSUE THREAD

**Issue by JohanWinther** [lindenb/makefile2graph#26]
My dependency tree is rather large. Is it possible for make to not expand the variables and keep the variable names to reduce the number of edges in the graph? I.e. it won't output an edge for each C-file, instead it will output one edge for the variable where the C-files are set. I understand that this is something for make to implement, but I can't find anything in the manual.

**Comment by JohanWinther** [comment]
Or perhaps you could combine files which have the same parent folder into one edge, that would also reduce the number of edges.

**Comment by lindenb** [comment]
isn't it a problem that is specific to **make** itself ?

**Comment by JohanWinther** [comment]
> 
> 
> isn't it a problem that is specific to **make** itself ?

Yes, that's true. However I could perhaps also solve the problem by only saving unique folders as edges rather than all files. Is it technically possible to change the program to do that? Then I may make a pull request.

**Comment by JohanWinther** [comment]
I figured I can modify the dot file after generation instead of cluttering the program.
