### ISSUE TITLE
Empty graph for GNU Make 4.2.1?

### ISSUE THREAD

**Issue by jilljenn** [lindenb/makefile2graph#27]
I tried makefile2graph on its own Makefile and got an empty graph.

My version of make is: 4.2.1.

**Comment by lindenb** [comment]
thank you for the report; I'm afraid I won't be able to test it quickly with a recent version of make

**Comment by jilljenn** [comment]
OK; I'm pretty sure you want to merge the PR that provides a "better green".
BTW, why do you need make -Bnd and not just the content of the Makefile?

**Comment by jilljenn** [comment]
OK I got it! You need to have your bash in English first: `export LC_ALL=C`
I managed to get my graph again. Thanks!
