### ISSUE TITLE
Use colorblind safe colours for ellipses

### ISSUE THREAD

**Issue by sje30** [lindenb/makefile2graph#28]
Hi,

Thanks for this tool; I'm using it to write a tutorial.  Would you consider swapping the colours for the ellipses of each file?  At the moment they are green/red.  This is not a good choice for colorblind readers.  A better default (and perhaps softer) might be to take some colours from the palettes available at: https://colorbrewer2.org/#type=qualitative&scheme=Set2&n=3

e.g. I've changed my local copy make2graph L375 to:

```
				(t->must_remake?"#fc8d62":"#66c2a5") /* https://colorbrewer2.org/#type=qualitative&scheme=Set2&n=3 */
```

Best wishes, stephen

**Comment by lindenb** [comment]
close afer https://github.com/lindenb/makefile2graph/pull/24
