### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by arash-mazidi** [lindenb/makefile2graph#35]
Hi,

I compile a c program to Webassembly. It generates .wasm files.
I want to find the source .c file that generates .wasm file. 
Does your tool find this relation between .c file and .wasm file?
I mean, can we consider .wasm file is depended on .c file. So, there is a dependency between .wasm file and .c file.

**Comment by lindenb** [comment]
this tools just convert a Makefile to a graph.

If you have a Makefile, you can find the *.c depedencies just by running `make -n file.wasm`

**Comment by alleykk** [comment]
Thanks.
What does it mean : "sub-makefiles are not supported". What does "sub-makefiles" mean?

If I want to run this tool,
1- I should clone the repository in Drive C:
2- I should navigate to directory that included Makefile.
3- Run command : make -Bnd | make2graph

Then, it will produce "output.dot" in the same directory!
Is it true?

**Comment by lindenb** [comment]
>  What does "sub-makefiles" mean?

https://www.google.com/search?channel=fs&client=ubuntu-sn&q=sub-makefiles
